package io.github.takenoko4096.starlight.render.model.builtin

enum class NonClientBuiltinModelTemplate(vararg val textureSlots: NonClientBuiltinTextureSlot) {
    CUBE(
        NonClientBuiltinTextureSlot.PARTICLE,
        NonClientBuiltinTextureSlot.NORTH,
        NonClientBuiltinTextureSlot.SOUTH,
        NonClientBuiltinTextureSlot.EAST,
        NonClientBuiltinTextureSlot.WEST,
        NonClientBuiltinTextureSlot.UP,
        NonClientBuiltinTextureSlot.DOWN
    ),
    CUBE_COLUMN(
        NonClientBuiltinTextureSlot.SIDE,
        NonClientBuiltinTextureSlot.END
    ),
    CUBE_ALL(
        NonClientBuiltinTextureSlot.ALL
    ),
    CROP(
        NonClientBuiltinTextureSlot.CROP
    ),
    SLAB_TOP(
        NonClientBuiltinTextureSlot.TOP,
        NonClientBuiltinTextureSlot.BOTTOM,
        NonClientBuiltinTextureSlot.SIDE
    ),
    SLAB_BOTTOM(
        NonClientBuiltinTextureSlot.TOP,
        NonClientBuiltinTextureSlot.BOTTOM,
        NonClientBuiltinTextureSlot.SIDE
    ),
    FLAT_ITEM(
        NonClientBuiltinTextureSlot.LAYER0
    ),
    FLAT_HANDHELD_ITEM(
        NonClientBuiltinTextureSlot.LAYER0
    ),
    FLAT_HANDHELD_ROD_ITEM(
        NonClientBuiltinTextureSlot.LAYER0
    ),
    FLAT_HANDHELD_MACE_ITEM(
        NonClientBuiltinTextureSlot.LAYER0
    );
}
